### ISSUE TITLE
remote tracking branches are not getting cleaned up

### ISSUE THREAD

**Issue by pcal43** [pcal43/fastback#117]

**Comment by pcal43** [comment]
gc should blow away any stragglers

**Comment by pcal43** [comment]
```
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/3f976ef7-5179-4006-8133-9f65d43866f8/2022-09-05_01-35-35=356c64e176ecfd1c2753e600f94658dff616af55(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/3f976ef7-5179-4006-8133-9f65d43866f8/2022-09-05_23-28-34=fc377e3f1e5d8736734dfe28a25a96563bdce6e4(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/3f976ef7-5179-4006-8133-9f65d43866f8/2022-09-06_09-22-17=1a23ccf4903421b86b6cfbde36f28140b9631fae(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-04_02-55-14=2e0d46505460ad847b338b55440835bc5beab02f(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-04_02-57-20=1ad176bdbc66c69169e5d8f8c054a9cbb8e70dcb(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-05_23-03-56=b11a49a9f939d4111974c82a9366332a9cdec2e7(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-05_23-41-37=9a4b2a92fbecce4f00ffe9649f153ead41131e5b(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-05_23-58-54=8547f02161f8450bc1e1bf2a9b3a4206a12722d1(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-02-53=ea8a3fcf6202f1fc5b01c0e2602d9ce8ba0f680c(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-05-57=eaff298b03aab76f7c79e8b5a2ab893f5f478733(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-06-46=c236d4d7a32e228cffd6605ccf0b7026df8a9856(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-08-42=2ec90275d0b35efac7e55b598b9670f5524e4e3b(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-19-12=75e41c493aeabe96c238537610cf2ea3c90909bb(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-20-38=7155aa782e0f31d3c3ac1e797fa9157718c003f7(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-21-41=d491a56715d9fe99964b5cb619e4caf799f09b96(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-23-53=8e828ba9ead017ac441ef2d78dcaea92340fd96e(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-25-18=a3098cc37205eadc09057406722ebd5c3e4d47e4(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-38-02=b846b0afb55f6048a93cd2b14d5e75190a6eb7ee(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-38-24=90ec66da02c95b732930af727b6e2179d7594e66(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_00-56-03=a1d0b3526910b3f45e49e0077a88884db19557a4(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_01-09-10=90fea6126fee68e2f49cdf6a977be24d9ab76e19(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_09-18-34=baa405d7a2351d77bfafb7087127ebb077af5048(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_14-28-25=726bcd095ea692a685e1e876a1e0041b1fce62df(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_16-49-35=be616da3de934fc3867f79c21f04cfcaf511a170(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_16-50-22=e90bf50b9d7623ed5f26cd62a387f46ccd0f915d(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_16-51-28=6a38aff3d3ec31204992edf7559dc26bced00613(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_17-27-51=e68418012435da239792ffe75d3dd7a377b6787b(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_17-29-16=747d435340e293767da731de52b978d786a150fd(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_17-33-46=cee0dfa73db050680321a7755f6c0e1b18e6ce80(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_17-34-40=2722b40cfe688908d514b19a7e2034fe3abead63(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_17-35-19=aeeb0afb73b186b3a22ec206471e35a461e31f37(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_17-43-28=2805548098cee8c5aa0f159cd3ce3ea8d2f3e146(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_17-53-43=b7a2896bd34730467039a5637faf8e7c26eb88d2(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot/bd867226-4959-4560-988c-540904a30871/2022-09-06_18-11-15=22f2eb1112731ed06efdec88976dcca6285a653a(-1)]
[21:01:08] [Server thread/WARN]: Non-branch ref returned by branchList: Ref[refs/remotes/origin/snapshot
```

**Comment by pcal43** [comment]
They're definitely not getting deleted.  Lot of disk space being wasted.

**Comment by Magicrafter13** [comment]
Not sure if this is identical, but in the current version of the mod I seem to be having an issue with remote pruning/gc.

I run `backup prune` followed by `backup gc` and I end up with the designated 5 fixed snapshots (output from `backup list`:
```
2023-06-22_00-30-13
2023-07-02_15-38-58
2023-07-02_15-41-43
2023-07-02_15-48-29
2023-07-02_15-50-30
2023-07-02_19-09-46
```

However, on GitLab it still shows many branches:
![image](https://github.com/pcal43/fastback/assets/29127566/678cceaf-de25-41bc-bfb5-a97bc5698a4a)

I also tried `backup remote-prune` but that errors out:
```
[fastback] Command execution failed.
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at net.pcal.fastback.retention.RetentionPolicyCodec.decodePolicy(RetentionPolicyCodec.java:47) ~[transformed-mod-fastback.i0:0/:?]
        at net.pcal.fastback.tasks.LocalPruneTask.doPrune(LocalPruneTask.java:83) ~[transformed-mod-fastback.i0:0/:?]
        at net.pcal.fastback.tasks.RemotePruneTask.call(RemotePruneTask.java:60) ~[transformed-mod-fastback.i0:0/:?]
        at net.pcal.fastback.commands.RemotePruneCommand.lambda$remotePrune$1(RemotePruneCommand.java:63) ~[transformed-mod-fastback.i0:0/:?]
        at net.pcal.fastback.commands.Commands.lambda$gitOp$1(Commands.java:111) ~[transformed-mod-fastback.i0:0/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```
