### ISSUE TITLE
error on shutdown if backups not enabled on world

### ISSUE THREAD

**Issue by ghost** [pcal43/fastback#167]
### Relevant Error:
```
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/game-server/Minecraft/HGG/world
        at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:627) ~[org_eclipse_jgit_org_eclipse_jgi206071550-r-f0955f5ce674565a.jar:?]
        at org.eclipse.jgit.api.Git.open(Git.java:93) ~[org_eclipse_jgit_org_eclipse_jgi206071550-r-f0955f5ce674565a.jar:?]
        at org.eclipse.jgit.api.Git.open(Git.java:73) ~[org_eclipse_jgit_org_eclipse_jgi206071550-r-f0955f5ce674565a.jar:?]
        at net.pcal.fastback.LifecycleUtils.onWorldStop(LifecycleUtils.java:84) ~[fastback-0.7.3+1.19.2.jar:?]
        at net.pcal.fastback.fabric.FabricServerInitializer.lambda$onInitializeServer$1(FabricServerInitializer.java:46) ~[fastback-0.7.3+1.19.2.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$6(ServerLifecycleEvents.java:76) ~[fabric-lifecycle-events-v1-2.2.0+33ffe9ec90-fbd9228dd8adfc4d.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bhg000$afterShutdownServer(MinecraftServer:5811) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.shutdown(MinecraftServer:609) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.MinecraftDedicatedServer.shutdown(MinecraftDedicatedServer:547) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Full Log:
https://mclo.gs/PNe4Uhc

**Comment by pcal43** [comment]
hmm.  did this happen on a world that did not have backups enabled?  that might be it.

**Comment by ghost** [comment]
I had never disabled backups on the world - unless they start off that way?

EDIT: I can't even find a config file for this mod, anywhere...

**Comment by ghost** [comment]
Ah okay, I realise now I have to actually enable it myself first.

Kinda odd, not like any other backup plugin/mod I've ever used - should this behaviour maybe be inverted by default? I understand it's in the documentation, but at the same time, I imagine I wouldn't be the only one to assume the operation is similar to other tools.

**Comment by pcal43** [comment]
Confirmed the bug.

re: enabling by default, i guess I could do it.  But it's pretty to imagine cases where they have the mod installed but dont want to be creating a backup.  Esp. in singleplayer.
