### ISSUE TITLE
Backup fails because of missing file?

### ISSUE THREAD

**Issue by christenlanger** [pcal43/fastback#228]
I've just installed the mod on our server and it is failing to initiate the backup. Here is the log:
```
[15:03:33] [Server thread/INFO]: Saving before backup
[15:03:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[15:03:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[15:03:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[15:03:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[15:03:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:03:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[15:03:33] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[15:03:33] [Server thread/INFO]: Starting backup
[15:03:33] [pool-3-thread-2/ERROR]: Command execution failed.
java.nio.file.NoSuchFileException: /serverdata/serverfiles/world/fastback/world.uuid
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.nio.file.Files.readAllBytes(Files.java:3289) ~[?:?]
	at java.nio.file.Files.readString(Files.java:3367) ~[?:?]
	at java.nio.file.Files.readString(Files.java:3326) ~[?:?]
	at net.pcal.fastback.repo.RepoImpl.getWorldUuid(RepoImpl.java:117) ~[fastback-0.13.0+1.20.1.jar:?]
	at net.pcal.fastback.repo.CommitUtils.doCommitSnapshot(CommitUtils.java:54) ~[fastback-0.13.0+1.20.1.jar:?]
	at net.pcal.fastback.repo.RepoImpl.doCommitSnapshot(RepoImpl.java:90) ~[fastback-0.13.0+1.20.1.jar:?]
	at net.pcal.fastback.commands.Commands.lambda$gitOp$2(Commands.java:143) ~[fastback-0.13.0+1.20.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[15:03:33] [pool-3-thread-2/INFO]: An unexpected backup error occurred. See log for details.
```

**Comment by pcal43** [comment]
<strike>Hmm.  Does that file exist?  Do you see any messages earlier up in the log about it failing to create that file?
```
/serverdata/serverfiles/world/fastback/world.uuid
```

Also, what did you do exactly?  
```
/backup enable
/backup local
```
???</strike>

**Comment by pcal43** [comment]
<strike>Also do you happen to have any symlinks involved here?</strike>

**Comment by pcal43** [comment]
<strike>...one thing you can try is 
* delete the `.git` directory (assuming you don't care about the backups)
* run `/backup enable` again.  (that's when the uuid file is supposed to get created)
* check to see if you have that file now.  or if you see errors instead</strike>

**Comment by pcal43** [comment]
...oh, shoot never mind.  I did break this yesterday.  Will have a fix shortly.

**Comment by pcal43** [comment]
should be fixed here:  https://modrinth.com/mod/fastback/version/0.14.0+1.20.1
thanks for the report.

**Comment by christenlanger** [comment]
I was going to apologize for the late reply but glad that I got to report an actual issue. Thank you very much!

**Comment by christenlanger** [comment]
I would also like to confirm that it's backup is now working properly. I am running the minecraft server in a docker container.
