### ISSUE TITLE
Backups fail - fatal: confused by unstable object source data for example

### ISSUE THREAD

**Issue by McMelonTV** [pcal43/fastback#318]
Hey, my backups keep failing with the error below. It worked before players started actually playing survival. After that this keeps popping up everytime a backup runs.
```
[21:35:19] [pool-5-thread-5/ERROR]: [STDERR] fatal: confused by unstable object source data for 3302de592c5eaec86662966e7564b207d2461348
[21:35:19] [pool-5-thread-5/ERROR]: [STDOUT] add 'entities/r.2.0.mca'
[21:35:19] [pool-5-thread-5/ERROR]: Exit 128 when executing: git -C /home/container/world add -v .
net.pcal.fastback.utils.ProcessException: Exit 128 when executing: git -C /home/container/world add -v .
        at net.pcal.fastback.utils.ProcessUtils.doExec(ProcessUtils.java:75) ~[fastback-0.17.0+1.20.4-fabric.jar:?]
        at net.pcal.fastback.utils.ProcessUtils.doExec(ProcessUtils.java:44) ~[fastback-0.17.0+1.20.4-fabric.jar:?]
        at net.pcal.fastback.repo.CommitUtils.native_commit(CommitUtils.java:133) ~[fastback-0.17.0+1.20.4-fabric.jar:?]
        at net.pcal.fastback.repo.CommitUtils.doCommitSnapshot(CommitUtils.java:82) ~[fastback-0.17.0+1.20.4-fabric.jar:?]
        at net.pcal.fastback.repo.RepoImpl.doCommitSnapshot(RepoImpl.java:121) ~[fastback-0.17.0+1.20.4-fabric.jar:?]
        at net.pcal.fastback.commands.SchedulableAction$2.lambda$getTask$0(SchedulableAction.java:51) ~[fastback-0.17.0+1.20.4-fabric.jar:?]
        at net.pcal.fastback.mod.AutosaveListener.lambda$run$0(AutosaveListener.java:72) ~[fastback-0.17.0+1.20.4-fabric.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

FastBack Info
-------------
[21:40:30] [Server thread/INFO]: FastBack version: 0.17.0+1.20.4-fabric
[21:40:30] [Server thread/INFO]: native git installed: true
[21:40:31] [Server thread/INFO]:    git: git version 2.34.1
[21:40:31] [Server thread/INFO]:    git-lfs: git-lfs/3.4.1 (GitHub; linux amd64; go 1.21.1)
[21:40:31] [Server thread/INFO]: World size: 24 GB
[21:40:31] [Server thread/INFO]: Local backup size: 24 GB

**Comment by pcal43** [comment]
Tough to say.  That error is coming deep from within the bowels of git.  I've never seen it before.

A quick google search suggests one of the following:
- You're getting unlucky with timing and world files are getting written at just the wrong time.  I try to lock minecraft from flushing updates while backup is happening but maybe there's gap.
- A really big file is getting added (1gb+ say)
- Some sort of disk corruption

I'll leave this open but I'm unlikely to have time to investigate it myself.

**Comment by RaeTheGit** [comment]
I seem to be running into the same issue. The server console reports:

```
Creating backup snapshot 2024-03-21_10-06-05

pool-20-thread-4/ERROR

Exit 128 when executing: git -C /home/amp/.ampdata/instances/WeirdMods201/Minecraft commit -m u2YH/2024-03-21_10-06-05

Console

net.pcal.fastback.utils.ProcessException: Exit 128 when executing: git -C /home/amp/.ampdata/instances/WeirdMods201/Minecraft commit -m u2YH/2024-03-21_10-06-05
at net.pcal.fastback.utils.ProcessUtils.doExec(ProcessUtils.java:75) ~[fastback-0.15.6+1.20.1-forge.jar%23407!/:?] {re:classloading}
at net.pcal.fastback.utils.ProcessUtils.doExec(ProcessUtils.java:44) ~[fastback-0.15.6+1.20.1-forge.jar%23407!/:?] {re:classloading}
at net.pcal.fastback.repo.CommitUtils.native_commit(CommitUtils.java:140) ~[fastback-0.15.6+1.20.1-forge.jar%23407!/:?] {re:classloading}
at net.pcal.fastback.repo.CommitUtils.doCommitSnapshot(CommitUtils.java:82) ~[fastback-0.15.6+1.20.1-forge.jar%23407!/:?] {re:classloading}
at net.pcal.fastback.repo.RepoImpl.doCommitSnapshot(RepoImpl.java:121) ~[fastback-0.15.6+1.20.1-forge.jar%23407!/:?] {re:classloading}
at net.pcal.fastback.commands.LocalCommand.lambda$run$1(LocalCommand.java:67) ~[fastback-0.15.6+1.20.1-forge.jar%23407!/:?] {re:classloading}
at net.pcal.fastback.commands.Commands.lambda$gitOp$0(Commands.java:125) ~[fastback-0.15.6+1.20.1-forge.jar%23407!/:?] {re:classloading}
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?] {}
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?] {}
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] {}
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] {}
at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

pool-20-thread-4/INFO

fastback.chat.commit-failed
Backup complete. Time elapsed: 1s
```

Is there any detail I can provide to help get to the bottom of this?
Just in case, this is MC 1.20.1 with NeoForge as modloader.

**Comment by McMelonTV** [comment]
It seemed to have been caused by a logging mod for me. Are you running anything like that by a chance?

**Comment by tbritt10** [comment]
This error seems to pop for me everytime if a backup runs while I am logged in to the game with my character. I can disconnect and run backup full from the server console no issue. 

```
[09:16:36] [pool-12-thread-505/INFO]: Starting auto-backup
[09:16:37] [pool-12-thread-505/INFO]: The server is starting a backup.
[09:17:42] [pool-12-thread-505/ERROR]: [STDERR] warning: in the working copy of '.gitattributes', LF will be replaced by CRLF the next time Git touches it
[09:17:42] [pool-12-thread-505/ERROR]: [STDERR] warning: in the working copy of '.gitignore', LF will be replaced by CRLF the next time Git touches it
[09:17:42] [pool-12-thread-505/ERROR]: [STDERR] fatal: confused by unstable object source data for 7d2af20b995c0992faee05fb6439ba2a598121d1
[09:17:42] [pool-12-thread-505/ERROR]: Exit 128 when executing: git -C F:\Game Servers\JaveBedrockCombo\world add -v .
net.pcal.fastback.utils.ProcessException: Exit 128 when executing: git -C F:\Game Servers\JaveBedrockCombo\world add -v .
        at knot/net.pcal.fastback.utils.ProcessUtils.doExec(ProcessUtils.java:81) ~[fastback-0.26.0+1.21.7-fabric.jar:?]
        at knot/net.pcal.fastback.utils.ProcessUtils.doExec(ProcessUtils.java:44) ~[fastback-0.26.0+1.21.7-fabric.jar:?]
        at knot/net.pcal.fastback.repo.CommitUtils.native_commit(CommitUtils.java:133) ~[fastback-0.26.0+1.21.7-fabric.jar:?]
        at knot/net.pcal.fastback.repo.CommitUtils.doCommitSnapshot(CommitUtils.java:82) ~[fastback-0.26.0+1.21.7-fabric.jar:?]
        at knot/net.pcal.fastback.repo.RepoImpl.doCommitSnapshot(RepoImpl.java:121) ~[fastback-0.26.0+1.21.7-fabric.jar:?]
        at knot/net.pcal.fastback.commands.SchedulableAction$2.lambda$getTask$0(SchedulableAction.java:51) ~[fastback-0.26.0+1.21.7-fabric.jar:?]
        at knot/net.pcal.fastback.mod.AutosaveListener.lambda$run$0(AutosaveListener.java:72) ~[fastback-0.26.0+1.21.7-fabric.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by goldstargloww** [comment]
can confirm that @tbritt10's solution works! this error only happened the first time and backups work while players are online now, but that might change

**Comment by goldstargloww** [comment]
yeah, it doesn't work anymore. i've just been backing up upon shutdown now

**Comment by tmkop** [comment]
I am also having this issue. It happened right after backing up waystones.dat created by a waystones mod. I removed the waystone mod and got one successful backup, then these errors started back up always after world_clocks.dat which has a file size of 107 bytes. Any advice? I am playing single player. Is a backup created when the world closes automatically?


[20:08:42] [pool-7-thread-6/ERROR]: [STDERR] warning: in the working copy of '.gitattributes', LF will be replaced by CRLF the next time Git touches it
[20:08:42] [pool-7-thread-6/ERROR]: [STDERR] warning: in the working copy of '.gitignore', LF will be replaced by CRLF the next time Git touches it
[20:08:42] [pool-7-thread-6/ERROR]: [STDOUT] add 'data/minecraft/random_sequences.dat'
[20:08:42] [pool-7-thread-6/ERROR]: [STDOUT] add 'data/minecraft/scheduled_events.dat'
[20:08:42] [pool-7-thread-6/ERROR]: [STDOUT] add 'data/minecraft/scoreboard.dat'
[20:08:42] [pool-7-thread-6/ERROR]: [STDOUT] add 'data/minecraft/wandering_trader.dat'
[20:08:42] [pool-7-thread-6/ERROR]: [STDOUT] add 'data/minecraft/weather.dat'
[20:08:42] [pool-7-thread-6/ERROR]: [STDOUT] add 'data/minecraft/world_clocks.dat'
[20:08:42] [pool-7-thread-6/ERROR]: [STDERR] fatal: confused by unstable object source data for e68bad8a29e228aba1f38878286ace296e0d3fd7
[20:08:42] [pool-7-thread-6/ERROR]: Exit 128 when executing: git -C C:\Users\User\AppData\Roaming\ModrinthApp\profiles\It Really Wasnt Forever\saves\8_27_26 (1) add -v .
net.pcal.fastback.common.utils.ProcessException: Exit 128 when executing: git -C C:\Users\User\AppData\Roaming\ModrinthApp\profiles\It Really Wasnt Forever\saves\8_27_26 (1) add -v .
	at knot//net.pcal.fastback.common.utils.ProcessUtils.doExec(ProcessUtils.java:81)
	at knot//net.pcal.fastback.common.utils.ProcessUtils.doExec(ProcessUtils.java:44)
	at knot//net.pcal.fastback.common.repo.CommitUtils.native_commit(CommitUtils.java:133)
	at knot//net.pcal.fastback.common.repo.CommitUtils.doCommitSnapshot(CommitUtils.java:82)
	at knot//net.pcal.fastback.common.repo.RepoImpl.doCommitSnapshot(RepoImpl.java:123)
	at knot//net.pcal.fastback.common.commands.LocalCommand.lambda$run$0(LocalCommand.java:67)
	at knot//net.pcal.fastback.common.commands.Commands.lambda$gitOp$0(Commands.java:129)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[20:08:42] [Render thread/INFO]: [System] [CHAT] Backup failed.  See log for details.

**Comment by tmkop** [comment]
After distant horizons stopped generating new chunks or changing the LOD of rendered chunks this issue went away

**Comment by goldstargloww** [comment]
ohh distant horizons is a good shout, i'll keep that in mind
