### ISSUE TITLE
When run inside of a Docker container, remote doesn't work

### ISSUE THREAD

**Issue by schnow265** [pcal43/fastback#359]
I run this mod on a containerized minecraft server, and every time I try to do a full backup using `/backup full`, the following error appears in my logs:

```text
Dec 30 12:24:04 snowbox systemd-mcsvr[3276]: Caused by: org.eclipse.jgit.errors.TransportException: <my repo URL>: Authentication is required but no CredentialsProvider has been registered
Dec 30 12:24:04 snowbox systemd-mcsvr[3276]:         at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:689) ~[org_eclipse_jgit_org_eclipse_jgi309050840-r-1a9754f2407afcf8.jar:?]
Dec 30 12:24:04 snowbox systemd-mcsvr[3276]:         at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:467) ~[org_eclipse_jgit_org_eclipse_jgi309050840-r-1a9754f2407afcf8.jar:?]
Dec 30 12:24:04 snowbox systemd-mcsvr[3276]:         at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:170) ~[org_eclipse_jgit_org_eclipse_jgi309050840-r-1a9754f2407afcf8.jar:?]
Dec 30 12:24:04 snowbox systemd-mcsvr[3276]:         at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:131) ~[org_eclipse_jgit_org_eclipse_jgi309050840-r-1a9754f2407afcf8.jar:?]
Dec 30 12:24:04 snowbox systemd-mcsvr[3276]:         at net.pcal.fastback.repo.PushUtils.doPush(PushUtils.java:87) ~[fastback-0.15.6+1.20.1-fabric.jar:?]
Dec 30 12:24:04 snowbox systemd-mcsvr[3276]:         ... 8 more
```

When I do a `exec -it` into the container to get to a shell, I can git push manually with my stored credentials.

---

Output of `/backup info`:

```text
FastBack Info
-------------
FastBack version: 0.15.6+1.20.1-fabric
native git installed: true   
git: git version 2.43.0   
git-lfs: git-lfs/3.6.0 (GitHub; linux amd64; go 1.23.1)
Backup UUID: qVLD
World size: 434 MB
Local backup size: 551 MB
backup-enabled = true
remote-url = <my repo URL>
restore-directory = null
native-git-enabled = true
autoback-wait = 0
mods-backup-enabled = false
broadcast-enabled = true
broadcast-message = null
Shutdown action: full
Autoback action: none
No snapshot retention policy set.
No remote snapshot retention policy set.
```

**Comment by pcal43** [comment]
`Authentication is required but no CredentialsProvider has been registered`

This is a git configuration issue in your container.  Not really anything to do with fastback per se.
