### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by InsaanNotFound** [pcal43/fastback#86]
```
[15:11:47] [Render thread/FATAL]: Minecraft ran into a problem! Report saved to: C:\Users\Seba\Desktop\Gry\MultiMC\instances\Wildest-1.0\.minecraft\crash-reports\crash-2022-09-21_15.11.47-server.txt
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2022-09-21 15:11:47
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fastback'!
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.client.MinecraftClient.redirect$hle000$catchFabricInit(MinecraftClient:31454)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:459)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: Unable to load resource config\fastback\bin\enable
	at net.pcal.fastback.fabric.FabricClientModInitializer.onInitializeClient(FabricClientModInitializer.java:61)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 18 more
Caused by: java.io.FileNotFoundException: Unable to load resource config\fastback\bin\enable
	at net.pcal.fastback.utils.FileUtils.writeResourceToFile(FileUtils.java:60)
	at net.pcal.fastback.LifecycleUtils.copyConfigResources(LifecycleUtils.java:102)
	at net.pcal.fastback.LifecycleUtils.onClientStart(LifecycleUtils.java:42)
	at net.pcal.fastback.fabric.FabricClientModInitializer.onInitializeClient(FabricClientModInitializer.java:59)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
Mixins in Stacktrace: None found

-- Initialization --
Details:
Stacktrace:
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:28)
	at net.minecraft.class_310.redirect$hle000$catchFabricInit(class_310.java:31456)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		alujjdnd.ngrok.lan.mixin.WindowTitleMixin (ngroklan.mixins.json)
		com.blamejared.ambientenvironment.mixin.MixinMinecraft (ambientenvironment.fabric.mixins.json)
		fudge.notenoughcrashes.mixins.client.MixinMinecraftClient (notenoughcrashes.mixins.json)
		net.minecraftforge.mixin.client.MinecraftMixin (forgeconfigapiport.fabric.mixins.json)
		net.bettercombat.mixin.client.MinecraftClientAccessor (bettercombat.mixins.json)
		fuzs.puzzleslib.mixin.client.accessor.MinecraftAccessor (puzzleslib.fabric.mixins.json)
		ladysnake.sincereloyalty.mixin.client.MinecraftClientMixin (sincereloyalty.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		fishcute.celestial.mixin.MinecraftMixin (celestial.mixins.json)
		io.github.lucaargolo.accuratemaps.mixin.MinecraftClientMixin (accuratemaps.mixin.json)
		com.replaymod.core.mixin.MixinMinecraft (mixins.core.replaymod.json)
		chrono.mods.compassribbon.mixin.client.MinecraftMixin (cr-compass-ribbon.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_NoAuthInDev (mixins.iris.json)
		com.spanser.reacharound.mixin.client.MinecraftClientMixin (reacharound.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		fuzs.stylisheffects.mixin.client.MinecraftMixin (stylisheffects.fabric.mixins.json)
		ca.fxco.memoryleakfix.mixin.customPayloadLeak.MinecraftClient_freeBufferMixin (memoryleakfix.mixins.json)
		wraith.harvest_scythes.mixin.ClientMixin (harvestscythes.mixins.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		dev.stashy.extrasounds.mixin.HotbarSlotSound (extrasounds.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
		thecsdev.betterstats.client.mixin.MinecraftClientMixin (betterstats.client.mixins.json)
		draylar.omegaconfig.mixin.ClientMixin (omega-config.mixins.json)
		vazkii.patchouli.mixin.client.MixinMinecraft (patchouli_fabric.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		net.clayborn.accurateblockplacement.mixin.MinecraftClientMixin (accurateblockplacement.mixins.json)
		com.seibel.lod.fabric.mixins.events.MixinMinecraft (fabric.lod.mixins.json)
		ca.fxco.moreculling.mixin.blockstates.MinecraftClient_loadBlocksMixin (moreculling.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientMixin (languagereload.mixins.json)
		com.lodestar.aileron.mixin.MinecraftMixin (aileron-common.mixins.json)
		ca.fxco.moreculling.mixin.MinecraftClient_blockRenderManagerMixin (moreculling.mixins.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		dev.huskcasaca.effortless.mixin.PlayerActionMixin (effortless.mixins.json)
		net.fabricmc.fabric.mixin.networking.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.MinecraftClient_screenshotMixin (memoryleakfix.mixins.json)
		net.darkhax.bookshelf.mixin.client.AccessorMinecraft (bookshelf.common.mixins.json)
		net.bettercombat.mixin.client.MinecraftClientInject (bettercombat.mixins.json)
		net.dark_roleplay.gdarp.mixin.ClientPackFinderMixin (globaldataandresourcepacks.mixins.json)
		squeek.appleskin.mixin.MinecraftClientMixin (appleskin.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		eu.pb4.polymer.mixin.client.MinecraftClientMixin (polymer.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		fudge.notenoughcrashes.fabric.mixins.client.CatchInitMInecraftClientMixin (notenoughcrashes.fabric.mixins.json)
		com.replaymod.core.mixin.MinecraftAccessor (mixins.core.replaymod.json)
		dev.stashy.extrasounds.mixin.inventory.InventoryScreenSounds (extrasounds.mixins.json)
		committee.nova.pkstmystench.mixin.MinecraftClientMixin (pkstmystench.mixins.json)
		net.F53.HorseBuff.mixin.Client.InventoryAccessor (horsebuff.mixins.json)
		me.lucko.spark.fabric.mixin.MinecraftClientAccessor (spark.mixins.json)
		moriyashiine.enchancement.mixin.vanillachanges.cooldownpreventsusage.client.MinecraftClientMixin (enchancement.mixins.json)
		io.socol.betterthirdperson.mixin.MinecraftClientMixin (betterthirdperson.mixins.json)
		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (iceberg.mixins.json)
		zabi.minecraft.extraalchemy.mixin.client.MixinEntityOutline (extraalchemy.client.json)
		com.seibel.lod.fabric.mixins.MixinMinecraft (fabric.lod.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientAccessor (languagereload.mixins.json)
		dev.huskcasaca.effortless.mixin.ScreenMixin (effortless.mixins.json)
		moriyashiine.enchancement.mixin.perception.client.MinecraftClientMixin (enchancement.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinMinecraft (mixins.jgui.json)
		com.natamus.collective_fabric.fabric.mixin.MinecraftMixin (collective_fabric.mixins.json)
		org.betterx.bclib.mixin.client.MinecraftMixin (bclib.mixins.client.json)
		net.bunten.enderscape.client.mixin.MinecraftClientMixin (enderscape.client.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		dev.isxander.debugify.client.mixins.basic.mc46766.MinecraftClientMixin (debugify.client.mixins.json)
		com.replaymod.render.mixin.Mixin_SuppressFramebufferResizeDuringRender (mixins.render.replaymod.json)
		net.medievalweapons.mixin.client.MinecraftClientMixin (medievalweapons.mixins.json)
		ca.fxco.memoryleakfix.mixin.targetEntityLeak.MinecraftClient_targetClearMixin (memoryleakfix.mixins.json)
		io.github.lucaargolo.slotlock.mixin.MinecraftClientMixin (slotlock.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		fi.dy.masa.minihud.mixin.MixinMinecraftClient (mixins.minihud.json)
	net.minecraft.client.main.Main:
		fudge.notenoughcrashes.fabric.mixins.client.MixinMain (notenoughcrashes.fabric.mixins.json)
		io.github.ultimateboomer.smoothboot.mixin.client.MainMixin (smoothboot.mixins.json)
		ca.fxco.memoryleakfix.mixin.spongePoweredLeak.Main_clientLoadedMixin (memoryleakfix.mixins.json)

```

**Comment by pcal43** [comment]
hmm that's weird, I'll take a look.  thanks for the report

**Comment by pcal43** [comment]
oh, you're on windows.  I think I know what's going on.
